<?php
// $Id: faber_twitter.module,v 1.3 2010/04/15 20:08:28 doublethink Exp $

/*
 * Implementation of hook_block
 */
function faber_twitter_block($op = 'list', $delta = 0, $edit = array()) {
	if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Tweets from faberNovel\'s twitter'), 
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        $block = array(
          'subject' => t('Twitter'),
          'content' => theme('faber_twitter'));
        break;
    }
    return $block;
  }
}

/*
 * Implementation of hook_theme
 */
function faber_twitter_theme() {
  return array('faber_twitter' => array());
}

/*
 * Theme function to return dropdown html
 */
function theme_faber_twitter() {
	$result	=		'<div class="cls-faber-twitter">';
	$result	.=	'</div>';
  return $result;
}